package com.example.users;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller	// This class is a Controller
@RequestMapping(path="/user")
public class MyController {
	@Autowired //auto-generated by Spring, used to handle the user data
	private UserRepository userRepository;

	@PostMapping(path="/add")
	public @ResponseBody String addNewUser (@RequestParam String name
			, @RequestParam String email) {

		if(isValid(email)){
			User user = new User();
			user.setName(name);
			user.setEmail(email);
			userRepository.save(user);
			return "Saved";
		}else{
			return "Not Saved. Invalid Email";
		}

		
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<User> getAllUsers() {
		return userRepository.findAll();
	}

	@RequestMapping(path="/new")
	public String newUser (){
		return "newuser";
	}

	boolean isValid(String email) {
		String regex = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
		//match the input with the regular expression of email
		return email.matches(regex);
	 }
}
